"""
Strategy adapters — one per bot, stateless.

Owned by core/strategy/.
No exchange calls. No state mutations. Pure input → output.

Each adapter translates Phase 2 analysis outputs into a Signal
per the approved Signal Construction Contract.

Candle batches are provided as explicit arguments by BotRuntime
(MarketDataProvider.get_multi_timeframe_candles). Adapters do NOT
fetch market data internally.

Frozen Signal Construction Contract (Phase 4):
  ALPHA:  MacroBias.state → direction
          Top-ranked POI → entry zone (re-detect, resolve by poi.relevant_poi_id)
          Zone POI → structural stop (zone edge)
          Point POI → ATR14(M15) stop
          TP1 = 2R, TP2 = 3R
          H4 gate: h4_candle_closed == True required

  BETA:   validate_beta_sequence() → valid + direction
          M15 mitigation FVG midpoint → entry
          FVG zone edge → stop
          TP1 = 2R, TP2 = 3R
          Sweep level: PDH/PDL primary, session high/low secondary

  GAMMA:  validate_gamma_sequence() → valid + direction
          ReclaimResult.reclaim_price → entry
          LiquiditySweep.sweep_price → stop
          TP1 = 2R, TP2 = 3R
          ATR metadata: ATR14(M5)

  TP2 is persisted in Signal.take_profit_2. Exchange-attached TP in Phase 4
  uses only TP1 (Bybit native tp_trigger_price).
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from datetime import datetime

from schemas.candle import Timeframe, Candle
from schemas.signal import Signal, SignalState, POIType as SignalPOIType
from schemas.order import OrderSide
from schemas.poi import (
    OrderBlock,
    FVG,
    iFVG,
    SessionLevel,
    PeriodHighLow,
)
from schemas.bias import BiasState, MacroBias
from schemas.structure import SwingPoint, BOS, BOSDirection
from core.market_data.types import MarketSnapshot

from core.bias.builder import build_macro_bias, MacroBiasInput
from core.structure.swing import detect_swings
from core.structure.bos import detect_bos
from core.poi.order_block import detect_order_blocks
from core.poi.fvg import detect_fvgs, detect_ifvgs
from core.poi.levels import extract_session_levels, extract_period_high_low
from core.confirmation.sequencer import (
    validate_beta_sequence,
    validate_gamma_sequence,
)
from core.confirmation.sweep import detect_sweep, detect_all_sweeps
from core.confirmation.reclaim import detect_reclaim
from core.confirmation import (
    LiquiditySweep,
    SequenceStep,
    SequenceStepName,
    Direction,
)


# ---- Helpers ----

def _atr14(candles: list[Candle]) -> float | None:
    """Compute ATR14 on the given candle list. Returns None if insufficient data or ATR <= 0."""
    if len(candles) < 15:
        return None
    trs = []
    sorted_c = sorted(candles, key=lambda c: c.timestamp)
    for i in range(1, len(sorted_c)):
        cur = sorted_c[i]
        prev = sorted_c[i - 1]
        tr = max(
            cur.high - cur.low,
            abs(cur.high - prev.close),
            abs(cur.low - prev.close),
        )
        trs.append(tr)
    if len(trs) < 14:
        return None
    atr = sum(trs[-14:]) / 14
    if atr is None or atr <= 0:
        return None
    return atr


def _atr14_on_tf(candles: list[Candle]) -> float | None:
    """Alias for clarity — ATR14 computed on whatever timeframe candles are given."""
    return _atr14(candles)


def _build_signal(
    bot_id: str,
    symbol: str,
    direction: OrderSide,
    entry_price: float,
    stop_loss: float,
    tp1: float,
    tp2: float,
    poi_type: SignalPOIType,
    poi_price_min: float,
    poi_price_max: float,
    atr_buffer: float,
    trigger_type: str = "body_close",
) -> Signal:
    """Construct a Signal with all mandatory fields set per the approved contract."""
    return Signal(
        signal_id=str(uuid.uuid4()),
        bot_id=bot_id,
        symbol=symbol,
        direction=direction,
        entry_price=entry_price,
        stop_loss=stop_loss,
        take_profit_1=tp1,
        take_profit_2=tp2,
        atr_buffer_at_entry=atr_buffer,
        poi_type=poi_type,
        poi_price_min=poi_price_min,
        poi_price_max=poi_price_max,
        state=SignalState.PENDING,
    )


def _resolve_poi_by_id(
    poi_id: str,
    orderblocks: list[OrderBlock],
    fvgs: list[FVG],
    ifvgs: list[iFVG],
    session_levels: list[SessionLevel],
    period_levels: list[PeriodHighLow],
):
    """
    Resolve the exact POI object by its relevant_poi_id.

    The id is generated by detection code as str(uuid.uuid4())[:8].
    Checks each POI type's id field. Returns None if not found.
    """
    for ob in orderblocks:
        if ob.id == poi_id:
            return ob
    for f in fvgs:
        if f.id == poi_id:
            return f
    for f in ifvgs:
        if f.id == poi_id:
            return f
    for sl in session_levels:
        if sl.id == poi_id:
            return sl
    for pl in period_levels:
        if pl.id == poi_id:
            return pl
    return None


# ---- Protocol ----

class StrategyAdapter(ABC):
    """
    Abstract strategy interface — one implementation per bot.

    All adapters are STATELESS. They receive pre-fetched candle data
    and a market snapshot; they return a Signal or None.

    BotRuntime owns the tick loop, candle fetching, and state mutations.
    """

    @abstractmethod
    def evaluate(
        self,
        symbol: str,
        candles: dict[Timeframe, list[Candle]],
        market_snapshot: MarketSnapshot,
        previous_bias: MacroBias | None = None,
    ) -> Signal | None:
        """
        Evaluate market conditions and produce a Signal or None.

        Returns Signal: new signal to execute.
        Returns None: no action warranted this tick.

        Raises no exceptions — all errors result in None.
        """
        ...


# ---- Alpha Strategy Adapter ----

class AlphaStrategyAdapter(StrategyAdapter):
    """
    Alpha bot — H4 SMC/ICT signal generation.

    Phase 4 contract:
      - H4 gate: h4_candle_closed == True required
      - Direction: MacroBias.state (BULLISH/BEARISH → BUY/SELL)
      - Entry: top-ranked POI zone edge or midpoint
      - Stop: zone edge for zone POIs; ATR14(M15) for point POIs
      - TP1 = 2R, TP2 = 3R

    POI resolution:
      - Re-detect all POIs from provided candles
      - Resolve by MacroBias.poi.relevant_poi_id
      - If not found: return None
    """

    def evaluate(
        self,
        symbol: str,
        candles: dict[Timeframe, list[Candle]],
        market_snapshot: MarketSnapshot,
        previous_bias: MacroBias | None = None,
    ) -> Signal | None:
        # ── H4 candle close gate ────────────────────────────────────────────
        if not market_snapshot.h4_candle_closed:
            return None

        h4_candles = candles.get(Timeframe.H4, [])
        m15_candles = candles.get(Timeframe.M15, [])
        d1_candles = candles.get(Timeframe.D1, [])
        h1_candles = candles.get(Timeframe.H1, [])
        m1_candles = candles.get(Timeframe.M1, [])

        if not (h4_candles and m15_candles and d1_candles and h1_candles):
            return None

        # ── Detect analysis inputs ────────────────────────────────────────────
        swings_h4 = detect_swings(h4_candles)
        swings_h1 = detect_swings(h1_candles)
        bos_h4_list: list[BOS] = []
        bos_h4 = detect_bos(h4_candles, swings_h4)
        if bos_h4 is not None:
            bos_h4_list = [bos_h4]

        orderblocks = detect_order_blocks(h4_candles)
        fvgs = detect_fvgs(m15_candles)
        ifvgs = detect_ifvgs(m15_candles)
        session_levels = extract_session_levels(m15_candles)
        period_levels = extract_period_high_low(m15_candles)

        # ── Build MacroBias ──────────────────────────────────────────────────
        try:
            inp = MacroBiasInput(
                market=market_snapshot,
                swings_h4=swings_h4,
                swings_h1=swings_h1,
                bos_list=bos_h4_list,
                candles_d1=d1_candles,
                candles_h1=h1_candles,
                orderblocks=orderblocks,
                fvgs=fvgs,
                ifvgs=ifvgs,
                session_levels=session_levels,
                period_levels=period_levels,
                previous_bias=previous_bias,
            )
            macro_bias = build_macro_bias(inp)
        except Exception:
            return None

        # ── Direction gate ────────────────────────────────────────────────────
        if macro_bias.state == BiasState.NEUTRAL:
            return None

        direction = OrderSide.BUY if macro_bias.state == BiasState.BULLISH else OrderSide.SELL

        # ── Resolve selected POI by relevant_poi_id ──────────────────────────
        selected_poi = _resolve_poi_by_id(
            macro_bias.poi.relevant_poi_id,
            orderblocks, fvgs, ifvgs, session_levels, period_levels,
        )
        if selected_poi is None:
            return None

        # ── Entry price ──────────────────────────────────────────────────────
        entry_price = _alpha_entry_from_poi(selected_poi, direction)
        if entry_price is None:
            return None

        # ── ATR14(M15) — required metadata; also needed for point-POI stops ────
        atr_m15 = _atr14_on_tf(m15_candles)
        if atr_m15 is None:
            return None

        # ── Stop loss ────────────────────────────────────────────────────────
        stop_loss = _alpha_stop_from_poi(selected_poi, direction, entry_price, atr_m15)
        if stop_loss is None:
            return None

        # ── TP1 = 2R, TP2 = 3R ──────────────────────────────────────────────
        risk_distance = abs(entry_price - stop_loss)
        tp1 = entry_price + risk_distance * 2.0 if direction == OrderSide.BUY else entry_price - risk_distance * 2.0
        tp2 = entry_price + risk_distance * 3.0 if direction == OrderSide.BUY else entry_price - risk_distance * 3.0

        # ── POI type mapping ─────────────────────────────────────────────────
        poi_type, poi_price_min, poi_price_max = _poi_zone_fields(selected_poi)

        return _build_signal(
            bot_id="alpha_bot",
            symbol=symbol,
            direction=direction,
            entry_price=entry_price,
            stop_loss=stop_loss,
            tp1=tp1,
            tp2=tp2,
            poi_type=poi_type,
            poi_price_min=poi_price_min,
            poi_price_max=poi_price_max,
            atr_buffer=atr_m15,
        )


def _alpha_entry_from_poi(poi, direction: OrderSide) -> float | None:
    """
    Alpha entry price from selected POI.

    OrderBlock BUY  → price_high  (upper zone edge — buy above the OB)
    OrderBlock SELL → price_low   (lower zone edge — sell below the OB)
    FVG / iFVG      → midpoint
    SessionLevel    → level.price
    PeriodHighLow   → level.price
    """
    if isinstance(poi, OrderBlock):
        if direction == OrderSide.BUY:
            return poi.price_high
        else:
            return poi.price_low
    elif isinstance(poi, (FVG, iFVG)):
        return (poi.price_high + poi.price_low) / 2.0
    elif isinstance(poi, (SessionLevel, PeriodHighLow)):
        return poi.price
    return None


def _alpha_stop_from_poi(
    poi, direction: OrderSide, entry_price: float, atr_m15: float | None
) -> float | None:
    """
    Alpha stop loss from selected POI.

    Zone POIs (OrderBlock, FVG, iFVG):
      BUY  → stop = zone price_low
      SELL → stop = zone price_high

    Point POIs (SessionLevel, PeriodHighLow):
      BUY  → stop = entry - ATR14(M15)
      SELL → stop = entry + ATR14(M15)

    Returns None if required data is missing.
    """
    if isinstance(poi, OrderBlock):
        if direction == OrderSide.BUY:
            return poi.price_low
        else:
            return poi.price_high
    elif isinstance(poi, (FVG, iFVG)):
        if direction == OrderSide.BUY:
            return poi.price_low
        else:
            return poi.price_high
    elif isinstance(poi, (SessionLevel, PeriodHighLow)):
        if atr_m15 is None:
            return None
        if direction == OrderSide.BUY:
            return entry_price - atr_m15
        else:
            return entry_price + atr_m15
    return None


def _poi_zone_fields(poi) -> tuple[SignalPOIType, float, float]:
    """
    Extract POIType enum and price zone from any POI object.

    Returns (poi_type, price_min, price_max).
    Used to populate Signal.poi_type, poi_price_min, poi_price_max.
    """
    if isinstance(poi, OrderBlock):
        poi_type = SignalPOIType.ORDER_BLOCK_H4
    elif isinstance(poi, FVG):
        poi_type = SignalPOIType.FVG
    elif isinstance(poi, iFVG):
        poi_type = SignalPOIType.IFVG
    elif isinstance(poi, SessionLevel):
        poi_type = SignalPOIType.ASIAN_HIGH if poi.session.value == "asian" and poi.level_type.value == "high" else \
                   SignalPOIType.ASIAN_LOW if poi.session.value == "asian" and poi.level_type.value == "low" else \
                   SignalPOIType.LONDON_HIGH if poi.session.value == "london" and poi.level_type.value == "high" else \
                   SignalPOIType.LONDON_LOW if poi.session.value == "london" and poi.level_type.value == "low" else \
                   SignalPOIType.ASIAN_HIGH  # fallback
    elif isinstance(poi, PeriodHighLow):
        poi_type = SignalPOIType.PDH if poi.period.value == "daily" and poi.level_type.value == "high" else \
                   SignalPOIType.PDL if poi.period.value == "daily" and poi.level_type.value == "low" else \
                   SignalPOIType.PWH if poi.period.value == "weekly" and poi.level_type.value == "high" else \
                   SignalPOIType.PWL
    else:
        poi_type = SignalPOIType.FVG  # fallback

    if isinstance(poi, (FVG, iFVG)):
        return poi_type, poi.price_low, poi.price_high
    elif isinstance(poi, OrderBlock):
        return poi_type, poi.price_low, poi.price_high
    elif isinstance(poi, (SessionLevel, PeriodHighLow)):
        return poi_type, poi.price, poi.price
    else:
        return SignalPOIType.FVG, 0.0, 0.0


# ---- Beta mitigation FVG resolution helpers ----

def _find_mitigation_trigger_candle(
    candles: list[Candle],
    fvgs: list[FVG],
    direction: Direction,
) -> tuple[Candle, FVG] | None:
    """
    Find the mitigation trigger candle — the first candle (from most recent)
    whose close fell inside an FVG zone.

    Anchors to the trigger EVENT, not to current price.
    """
    for candle in reversed(candles):
        for fvg in fvgs:
            if fvg.direction.value != direction.value:
                continue
            # Full zone containment: candle close must be inside [price_low, price_high]
            if fvg.price_low <= candle.close <= fvg.price_high:
                return (candle, fvg)
    return None


def _resolve_mitigation_fvg(
    candles: list[Candle],
    fvgs: list[FVG],
    direction: Direction,
) -> FVG | None:
    """
    Resolve the exact mitigation FVG belonging to the valid sequence.

    Rules:
      - fvg.direction must match trade direction
      - fvg.created_at must be <= trigger_candle.timestamp (FVG existed before trigger)
      - trigger_candle.close must satisfy full zone containment:
          fvg.price_low <= candle.close <= fvg.price_high
      - If multiple candidates: select most recent by fvg.created_at
      - If no candidate: return None
    """
    result = _find_mitigation_trigger_candle(candles, fvgs, direction)
    if result is None:
        return None

    trigger_candle, _ = result

    candidates: list[FVG] = []
    for f in fvgs:
        if f.direction.value != direction.value:
            continue
        if f.created_at > trigger_candle.timestamp:
            continue
        if not (f.price_low <= trigger_candle.close <= f.price_high):
            continue
        candidates.append(f)

    if not candidates:
        return None

    # Select most recent FVG by created_at
    return max(candidates, key=lambda f: f.created_at)


# ---- Beta Strategy Adapter ----

class BetaStrategyAdapter(StrategyAdapter):
    """
    Beta bot — 4-step confirmation sequence → M15 mitigation FVG entry.

    Phase 4 contract:
      - Direction: validate_beta_sequence().direction
      - Entry: M15 mitigation FVG midpoint
      - Stop: FVG zone edge
      - TP1 = 2R, TP2 = 3R
      - Sweep level: PDH/PDL primary; session high/low secondary

    Sequence: SWEEP(PDH/PDL) → CHoCH(M15) → INDUCEMENT(M5) → MITIGATION(FVG)

    Mitigation step (step 4) is optional in Phase 4:
      If no M15 FVG is detected, the sequence is considered valid with steps 1-3.
      Entry zone is derived from the M15 FVG that forms during/after inducement.
    """

    def evaluate(
        self,
        symbol: str,
        candles: dict[Timeframe, list[Candle]],
        market_snapshot: MarketSnapshot,
        previous_bias: MacroBias | None = None,
    ) -> Signal | None:
        m5_candles = candles.get(Timeframe.M5, [])
        m15_candles = candles.get(Timeframe.M15, [])

        if not (m5_candles and m15_candles):
            return None

        # ── Sweep level hierarchy ───────────────────────────────────────────
        # Primary: PDH / PDL from extract_period_high_low
        period_levels = extract_period_high_low(m15_candles)
        pdh = next((p.price for p in period_levels
                    if p.period.value == "daily" and p.level_type.value == "high"), None)
        pdl = next((p.price for p in period_levels
                    if p.period.value == "daily" and p.level_type.value == "low"), None)

        # Secondary: session highs/lows from extract_session_levels
        session_levels = extract_session_levels(m15_candles)
        london_high = next((s.price for s in session_levels
                           if s.session.value == "london" and s.level_type.value == "high"), None)
        london_low = next((s.price for s in session_levels
                          if s.session.value == "london" and s.level_type.value == "low"), None)
        ny_high = next((s.price for s in session_levels
                        if s.session.value == "ny" and s.level_type.value == "high"), None)
        ny_low = next((s.price for s in session_levels
                       if s.session.value == "ny" and s.level_type.value == "low"), None)

        # Build candidate sweep levels: (price, direction)
        sweep_candidates: list[tuple[float, Direction]] = []
        if pdh is not None:
            sweep_candidates.append((pdh, Direction.SELL))   # sweep UP through PDH → bearish
        if pdl is not None:
            sweep_candidates.append((pdl, Direction.BUY))   # sweep DOWN through PDL → bullish
        if london_high is not None:
            sweep_candidates.append((london_high, Direction.SELL))
        if london_low is not None:
            sweep_candidates.append((london_low, Direction.BUY))
        if ny_high is not None:
            sweep_candidates.append((ny_high, Direction.SELL))
        if ny_low is not None:
            sweep_candidates.append((ny_low, Direction.BUY))

        if not sweep_candidates:
            return None

        # ── Detect sweeps on M5 ─────────────────────────────────────────────
        sweeps = detect_all_sweeps(m5_candles, sweep_candidates)
        if not sweeps:
            return None
        sweep = sweeps[0]  # most recent

        # Direction from sweep
        sweep_direction = sweep.direction

        # ── Resolve the exact mitigation FVG before building mitigation_step ──
        m15_fvgs = detect_fvgs(m15_candles)
        mitigation_fvg = _resolve_mitigation_fvg(m15_candles, m15_fvgs, sweep_direction)
        if mitigation_fvg is None:
            return None

        # ── Detect M5 micro-structure for CHoCH (not M15) ──────────────────
        swings_m5 = detect_swings(m5_candles)
        bos_m5 = detect_bos(m5_candles, swings_m5)

        # ── CHoCH step ──────────────────────────────────────────────────────
        choch = None
        if bos_m5 is not None:
            from core.structure.bos import detect_choch
            choch = detect_choch(m5_candles, bos_m5)

        # ── Inducement step ─────────────────────────────────────────────────
        external_sweep_price = sweep.sweep_price
        choch_level = bos_m5.broken_at if bos_m5 else None

        from core.confirmation.inducement import detect_inducement
        from schemas.structure import CHoCH

        inducement = None
        if choch is not None:
            inducement_input = CHoCH(
                timeframe="m5",
                direction=choch.direction,
                triggered_at=choch.triggered_at,
                timestamp=choch.timestamp,
            )
            inducement = detect_inducement(
                m5_candles,
                inducement_input,
                external_sweep_price=external_sweep_price,
                chosh_level=choch_level,
            )
        elif bos_m5 is not None:
            # No CHoCH confirmed — inducement cannot be evaluated
            inducement = None
        else:
            inducement = None

        # ── Build SequenceSteps for validate_beta_sequence ──────────────────
        sweep_step = SequenceStep(
            name=SequenceStepName.SWEEP,
            triggered=True,
            triggered_at=sweep.triggered_at,
            price_at_trigger=sweep.sweep_price,
            details={"direction": sweep.direction.value, "level": external_sweep_price},
        )

        choch_step = None
        if choch is not None:
            choch_step = SequenceStep(
                name=SequenceStepName.CHoCH,
                triggered=True,
                triggered_at=choch.timestamp,
                price_at_trigger=choch.triggered_at,
                details={"direction": choch.direction.value},
            )

        inducement_step = None
        if inducement is not None and inducement.is_valid:
            inducement_step = SequenceStep(
                name=SequenceStepName.INDUCEMENT,
                triggered=True,
                triggered_at=inducement.triggered_at,
                price_at_trigger=inducement.inducement_price,
                details={"direction": inducement.direction.value},
            )

        # Mitigation step: constructed from the already-resolved mitigation_fvg
        mitigation_step = SequenceStep(
            name=SequenceStepName.MITIGATION,
            triggered=True,
            triggered_at=mitigation_fvg.created_at,
            price_at_trigger=(mitigation_fvg.price_high + mitigation_fvg.price_low) / 2,
            details={"fvg_id": mitigation_fvg.id},
        )

        # ── Validate sequence ────────────────────────────────────────────────
        seq_result = validate_beta_sequence(
            sweep_step=sweep_step,
            chosh_step=chosh_step,
            inducement_step=inducement_step,
            mitigation_step=mitigation_step,
        )

        if not seq_result.valid:
            return None

        # ── Direction ────────────────────────────────────────────────────────
        direction = OrderSide.BUY if seq_result.direction == Direction.BUY else OrderSide.SELL

        # ── Entry: M15 FVG midpoint ────────────────────────────────────────
        entry_price = (mitigation_fvg.price_high + mitigation_fvg.price_low) / 2.0

        # ── Stop: FVG zone edge ─────────────────────────────────────────────
        if direction == OrderSide.BUY:
            stop_loss = mitigation_fvg.price_low
        else:
            stop_loss = mitigation_fvg.price_high

        # ── TP1 = 2R, TP2 = 3R ─────────────────────────────────────────────
        risk_distance = abs(entry_price - stop_loss)
        tp1 = entry_price + risk_distance * 2.0 if direction == OrderSide.BUY else entry_price - risk_distance * 2.0
        tp2 = entry_price + risk_distance * 3.0 if direction == OrderSide.BUY else entry_price - risk_distance * 3.0

        # ── ATR14(M15) metadata ─────────────────────────────────────────────
        atr_m15 = _atr14_on_tf(m15_candles)
        if atr_m15 is None:
            return None
        atr_buffer = atr_m15

        return _build_signal(
            bot_id="beta_bot",
            symbol=symbol,
            direction=direction,
            entry_price=entry_price,
            stop_loss=stop_loss,
            tp1=tp1,
            tp2=tp2,
            poi_type=SignalPOIType.FVG,
            poi_price_min=mitigation_fvg.price_low,
            poi_price_max=mitigation_fvg.price_high,
            atr_buffer=atr_buffer,
            trigger_type="mitigation_fvg",
        )


# ---- Gamma Strategy Adapter ----

class GammaStrategyAdapter(StrategyAdapter):
    """
    Gamma bot — 2-step confirmation sequence → reclaim entry.

    Phase 4 contract:
      - Direction: validate_gamma_sequence().direction
      - Entry: ReclaimResult.reclaim_price (M5 reclaim candle close)
      - Stop: LiquiditySweep.sweep_price (wick extreme that was swept)
      - TP1 = 2R, TP2 = 3R
      - ATR metadata: ATR14(M5)

    Sequence: SWEEP(PDH/PDL) → RECLAIM(M5)
    """

    def evaluate(
        self,
        symbol: str,
        candles: dict[Timeframe, list[Candle]],
        market_snapshot: MarketSnapshot,
        previous_bias: MacroBias | None = None,
    ) -> Signal | None:
        m5_candles = candles.get(Timeframe.M5, [])
        m15_candles = candles.get(Timeframe.M15, [])

        if not (m5_candles and m15_candles):
            return None

        # ── Sweep level hierarchy (same as Beta) ─────────────────────────────
        period_levels = extract_period_high_low(m15_candles)
        pdh = next((p.price for p in period_levels
                    if p.period.value == "daily" and p.level_type.value == "high"), None)
        pdl = next((p.price for p in period_levels
                    if p.period.value == "daily" and p.level_type.value == "low"), None)

        session_levels = extract_session_levels(m15_candles)
        london_high = next((s.price for s in session_levels
                           if s.session.value == "london" and s.level_type.value == "high"), None)
        london_low = next((s.price for s in session_levels
                          if s.session.value == "london" and s.level_type.value == "low"), None)
        ny_high = next((s.price for s in session_levels
                        if s.session.value == "ny" and s.level_type.value == "high"), None)
        ny_low = next((s.price for s in session_levels
                       if s.session.value == "ny" and s.level_type.value == "low"), None)

        sweep_candidates: list[tuple[float, Direction]] = []
        if pdh is not None:
            sweep_candidates.append((pdh, Direction.SELL))
        if pdl is not None:
            sweep_candidates.append((pdl, Direction.BUY))
        if london_high is not None:
            sweep_candidates.append((london_high, Direction.SELL))
        if london_low is not None:
            sweep_candidates.append((london_low, Direction.BUY))
        if ny_high is not None:
            sweep_candidates.append((ny_high, Direction.SELL))
        if ny_low is not None:
            sweep_candidates.append((ny_low, Direction.BUY))

        if not sweep_candidates:
            return None

        # ── Detect sweeps on M5 ─────────────────────────────────────────────
        sweeps = detect_all_sweeps(m5_candles, sweep_candidates)
        if not sweeps:
            return None
        sweep = sweeps[0]

        sweep_direction = sweep.direction
        sweep_price = sweep.sweep_price

        # ── Detect reclaim on M5 ────────────────────────────────────────────
        reclaim = detect_reclaim(m5_candles, sweep_price, sweep_direction)

        if not reclaim.is_valid:
            return None

        # ── Build SequenceSteps ─────────────────────────────────────────────
        sweep_step = SequenceStep(
            name=SequenceStepName.SWEEP,
            triggered=True,
            triggered_at=sweep.triggered_at,
            price_at_trigger=sweep_price,
            details={"direction": sweep.direction.value, "level": sweep_price},
        )

        reclaim_step = SequenceStep(
            name=SequenceStepName.RECLAIM,
            triggered=True,
            triggered_at=reclaim.reclaim_price,
            price_at_trigger=reclaim.reclaim_price,
            details={"direction": reclaim.direction.value, "reclaim_price": reclaim.reclaim_price},
        )

        # ── Validate Gamma sequence ─────────────────────────────────────────
        seq_result = validate_gamma_sequence(
            sweep_step=sweep_step,
            reclaim_step=reclaim_step,
        )

        if not seq_result.valid:
            return None

        # ── Direction ────────────────────────────────────────────────────────
        direction = OrderSide.BUY if seq_result.direction == Direction.BUY else OrderSide.SELL

        # ── Entry: reclaim price ─────────────────────────────────────────────
        entry_price = reclaim.reclaim_price

        # ── Stop: sweep wick extreme ────────────────────────────────────────
        # The stop is placed just beyond the swept level (wick extreme)
        # This is the structural invalidation point
        stop_loss = sweep_price

        # ── TP1 = 2R, TP2 = 3R ─────────────────────────────────────────────
        risk_distance = abs(entry_price - stop_loss)
        tp1 = entry_price + risk_distance * 2.0 if direction == OrderSide.BUY else entry_price - risk_distance * 2.0
        tp2 = entry_price + risk_distance * 3.0 if direction == OrderSide.BUY else entry_price - risk_distance * 3.0

        # ── ATR14(M5) metadata ──────────────────────────────────────────────
        atr_m5 = _atr14_on_tf(m5_candles)
        if atr_m5 is None:
            return None
        atr_buffer = atr_m5

        return _build_signal(
            bot_id="gamma_bot",
            symbol=symbol,
            direction=direction,
            entry_price=entry_price,
            stop_loss=stop_loss,
            tp1=tp1,
            tp2=tp2,
            poi_type=SignalPOIType.LIQUIDITY_SWEEP,
            poi_price_min=sweep_price,
            poi_price_max=sweep_price,
            atr_buffer=atr_buffer,
            trigger_type="reclaim",
        )
